### ISSUE TITLE
Code Review by Yutong Gao

### ISSUE THREAD

**Issue by Omelet123** [kev5/Go-Meet#9]
Hi, guys! I can see your group already made a big progress.  I'd like to show my understanding and suggestions about your project here.  According to the first two sprints presentation, I have a basic understanding of your project. It is a social application which can share information about activities around us. It can make more people come outside and make new friends. This is a very good idea. If your application finished, I'd like to try it. According to your code, I can see that you are using google map to realize the main functions. It is good to use open source but I think it will be better if you can add more comments in the code to indicate which part of the code is changed. So that other people can take over your job easily. I can see your group already build an android app. It has several basic functions like login and register. However, there are a lot of files in the main repository which I don't know their usefulness. I can find some of them already in the BasicLocationSample file. Some of them are totally commented out. I think it is better to make a much clear structure of your code. 
Hope my review will help you.

**Comment by kev5** [comment]
Thanks @Omelet123 for your valuable review. Your points are completely valid, and we assure that once we have a good prototype of our application up and running, we will work on our repository's file structure to make it easier for others to look at our code.
